# Generated by Django 4.0.4 on 2022-05-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('number_of_movies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField(max_length=1500)),
                ('release_date', models.DateField()),
                ('number_of_actors', models.IntegerField()),
                ('actors', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie.actor')),
            ],
        ),
    ]
