# Generated by Django 4.0.4 on 2022-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_number_of_actors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieActors',
            new_name='MovieActor',
        ),
        migrations.AddField(
            model_name='movie',
            name='no_of_actors',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
