# Generated by Django 4.0.4 on 2022-05-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_movieactors_movieactor_movie_no_of_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='no_of_actors',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
