# Generated by Django 4.0.4 on 2022-05-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_actor_number_of_movies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='number_of_movies',
            new_name='no_of_movies',
        ),
    ]
