# Generated by Django 4.0.4 on 2022-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_rename_number_of_movies_actor_no_of_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='no_of_movies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='no_of_actors',
            field=models.IntegerField(default=0),
        ),
    ]
