# Generated by Django 4.0.4 on 2022-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_actor_no_of_movies_alter_movie_no_of_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
